---
abstract: 'Socialtext WikiText Module'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WikiText-Socialtext
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  WikiText: 0.09
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
